version: "3.5"

services:
  nest:
    container_name: nestjs
    build: ./NestJS/
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: myuser
      DB_PASSWORD: mypassword
      DB_DATABASE: mydb
    ports:
      - 5000:5000
    networks:
      - back
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5432:5432
    networks:
      - back

networks:
  back:
    driver: bridge